ALTER SERVER ROLE [sysadmin] ADD MEMBER [LAPTOP-4270H2GK\ludho];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\SQLWriter];


GO
ALTER SERVER ROLE [sysadmin] ADD MEMBER [NT SERVICE\Winmgmt];

